### ISSUE TITLE
how to filter game types?

### ISSUE THREAD

**Issue by Chorobee** [aesuli/steam-crawler#16]
Hi, first Thanks for your code, may I ask how could I filter my game types when I use steam-game-crawler.py?

For example I just want to crawl those games with label - "indie" ? Can I filter directly from the web page? but how? I didnt find any filter.

Thanks for any reply.

**Comment by aesuli** [comment]
Hi, I'm sorry but this crawler is designed to download the full list of games, without any option for filtering.
You can try to do a filtering after the crawl on the games that match your criteria.
